### PR TITLE
Release 1.4.2

### PR DESCRIPTION
**Pull request by schuenke**
# This is meant as the final PR before the release of version 1.4.2

## The changelog is quite messy, so if nobody wants to create a more useful one, I would simply use the autogenerated changelog from GitHub, which I cleaned from temporary changes. Currently it would look like this:

---
## What's Changed
* bug fix to event_lib.py by @tblazey in https://github.com/imr-framework/pypulseq/pull/111
* sequence.py fix by @tblazey in https://github.com/imr-framework/pypulseq/pull/110
* latest make_sinc_pulse dont return gradient by default by @yupbank in https://github.com/imr-framework/pypulseq/pull/113
* Replace np.float with np.float64 by @btasdelen in https://github.com/imr-framework/pypulseq/pull/115
* Update gre_walkthrough for v1.4.0 by @btasdelen in https://github.com/imr-framework/pypulseq/pull/121
* Bug fixes that produced incorrect test reports by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/125
* Hacky fix for waveforms_and_times rf append floating point issue. by @btasdelen in https://github.com/imr-framework/pypulseq/pull/114
* Bug fixes in Sequence and make_trapezoid by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/128
* More pythonic handling of `shape_pieces` in `waveforms_and_times` by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/130
* Several bug fixes in `Sequence`, `add_gradients`, `make_trapezoid`, and `rotate` by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/132
* Added PNS calculations by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/131
* change sigpy dependency to GitHub repo by @schuenke in https://github.com/imr-framework/pypulseq/pull/135
* Performance improvements by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/133
* Add __init__,py to utils to help setuptools discover the package by @fzimmermann89 in https://github.com/imr-framework/pypulseq/pull/137
* Reworked piecewise polynomial implementation in Sequence to use scipy's PPoly by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/140
* Enh: New options in make_arbitrary_rf.py for adiabatic pulses by @wtclarke in https://github.com/imr-framework/pypulseq/pull/143
* Enh: Enable GitHub CI by @wtclarke in https://github.com/imr-framework/pypulseq/pull/142
* Bump sigpy version to 0.1.26 by @Andrew-Dupuis in https://github.com/imr-framework/pypulseq/pull/148
* BF: make_trapezoid with amplitude + duration as inputs. by @wtclarke in https://github.com/imr-framework/pypulseq/pull/146
* BF: Minor bug fixes in sequence.py and make_gauss_pulse.py by @wtclarke in https://github.com/imr-framework/pypulseq/pull/147
* BF: Refine argument options for make_block_pulse by @wtclarke in https://github.com/imr-framework/pypulseq/pull/151
* Fix BlockDurationRaster being ignored in read_seq.py by @gabuzi in https://github.com/imr-framework/pypulseq/pull/157
* Update confusing documentation for calc_duration.py by @gabuzi in https://github.com/imr-framework/pypulseq/pull/158
* Fixed `set_block` to give errors when multiple events of the same type are specified by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/141
* Various bug fixes, features, and cleanups by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/159
* Fixed `read_seq` for reading v1.3.1 sequence files by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/162
* Feature: `evaluate_labels` function in `Sequence` by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/164
* A few small bugfixes by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/165
* Bug fixes in `make_extended_trapezoid` and `add_gradients` by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/167
* Added gradient spectrum calculations by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/170
* Fix make_extended_trapezoid area by @schuenke in https://github.com/imr-framework/pypulseq/pull/171
* Added functionality to remove duplicate events by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/178
* Add continous deployment (CD) workflow by @schuenke in https://github.com/imr-framework/pypulseq/pull/173
* `remove_duplicates()` without `in_place = True` causes `signature_value` to be not updated after `write`. by @btasdelen in https://github.com/imr-framework/pypulseq/pull/179
* feat: add TRID label (GE interpreter). by @mcencini in https://github.com/imr-framework/pypulseq/pull/180
* Changed `get_gradients` to actually use extrapolation in the piecewise polynomial by @FrankZijlstra in https://github.com/imr-framework/pypulseq/pull/181

## New Contributors
* @tblazey made their first contribution in https://github.com/imr-framework/pypulseq/pull/111
* @yupbank made their first contribution in https://github.com/imr-framework/pypulseq/pull/113
* @FrankZijlstra made their first contribution in https://github.com/imr-framework/pypulseq/pull/125
* @fzimmermann89 made their first contribution in https://github.com/imr-framework/pypulseq/pull/137
* @wtclarke made their first contribution in https://github.com/imr-framework/pypulseq/pull/143
* @Andrew-Dupuis made their first contribution in https://github.com/imr-framework/pypulseq/pull/148
* @gabuzi made their first contribution in https://github.com/imr-framework/pypulseq/pull/157
* @mcencini made their first contribution in https://github.com/imr-framework/pypulseq/pull/180

**Full Changelog**: https://github.com/imr-framework/pypulseq/compare/1.4.0...1.4.1

### CODE REVIEW

**Comment by schuenke** [comment]
I would vote to remove the citations section from the Readme. Currently only citations until 2022 are included, but the section is already quite prominent. With all citations from 2022, 2023, 2024 this will get worse and keeping the list up to date is unnecessary work IMO.

**Comment by btasdelen** [comment]
@schuenke I agree that citations can be removed. I would argue that contributors can also be removed, as they are already shown by GitHub automatically.

**Comment by FrankZijlstra** [comment]
The auto-generated changelog looks fine to me.
I agree on removing citations, it would be hard to keep up-to-date anyway.
Removing contributors also seems fine.

One thing to consider about the version number and how we manage it going forward: the package version number (major, minor, revision) is written to the generated .seq files. I'm not 100% certain if any interpreter currently uses this to change any behaviour, but it could in theory have an effect. So if we start deviating from the Matlab Pulseq version numbers, we may need to keep a separate version number for the .seq file format.

**Comment by FrankZijlstra** [comment]
Apart from merging the last commits to the new release 1.4.1, are there any objections to going forward with this? Things left to do, etc?

**Comment by schuenke** [comment]
> Apart from merging the last commits to the new release 1.4.1, are there any objections to going forward with this? Things left to do, etc?

I don't think so. As suggested, I removed the contributors list from the README file. Further, I replaced the references in the beginning of the file with a link to the references section and added Philips to the list of supported hardware. 

Let's get your latest bug fix merged and then we should be good to go.


UPDATE: while writing this, I realized that some tests seem to fail... lets check this...

**Comment by schuenke** [comment]
I think we are now finally good to go now. Do we wanna stick with 1.4.1 now or directly jump to 1.4.2 to mirror the current Pulseq version? I think this is the last thing to decide 😁

**Comment by aTrotier** [comment]
Great work!
This PR fixes a lot of incompatibility issues with sigpy and numpy 2.0 :)

**Pull request merged**
