### PR TITLE
Add pre-commit workflow including ruff

### LINKED ISSUE #197: Define common code style (Linting/Formatting)
I am very happy to see that there are currently many people actively contributing to PyPulseq and even more happy that many people are motivated to help with our bigger code refactoring project. 👍 

However, currently we neither enforce nor specify a specific code style, which first of all may lead to style inconsistencies, which makes it harder for new contributors to choose the "correct" style for their code contributions, but it may also lead to unwanted code changes if people with different code formatters (like autopep8, black, ruff...) work on the same files. I usually try to commit relevant changes only, but just yesterday it happened to me as well that I commited changes my formatter did. 

So this Issue is meant to discuss possible code styles and more important potential ways to enforce these. For several other projects like [MRPro](https://github.com/PTB-MR/mrpro) or [BMCTool](https://github.com/schuenke/BMCTool) we use a combination of [MyPy](https://www.mypy-lang.org/) for type checking and [RUFF](https://docs.astral.sh/ruff/) as linter and code formatter. 

To enforce the defined code style and type checking BEFORE each commit, I really like the tool [pre-commit](https://pre-commit.com/). This can be installed locally and runs all defined checks (hooks) before beeing able to commit something. However, it's still possible to commit work-in-progress code without running the local checks using a `--no-verify` command. 

This is the current configuration we usually use for MyPy / RUFF / pre-commit:

### Relevant settings in pyproject.toml
```toml
[tool.mypy]
warn_return_any = false
check_untyped_defs = true
warn_no_return = true
warn_unreachable = true
exclude = ["docs"]
enable_error_code = ["ignore-without-code"]
warn_unused_ignores = true


[[tool.mypy.overrides]]
module = [
    "scipy.*",
]
ignore_missing_imports = true

[tool.ruff]
line-length = 120
extend-exclude = ["__init__.py"]
exclude = ["docs/**"]

[tool.ruff.lint]
select = [
    "A",   # flake8-builtins
    "ARG", # flake8-unused-arguments
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "COM", # flake8-commas
    "D",   # pydocstyle
    "E",   # pycodestyle errors
    "F",   # Pyflakes
    "FA",  # flake8-future-annotations
    "I",   # isort
    "N",   # pep8-naming
    "NPY", # NumPy-specific rules
    "RUF", # Ruff-specific rules
    "S",   # flake8-bandit
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
    "PIE", # flake8-pie
    # "PL",  # PyLint
    "PTH", # flake8-use-pathlib
    "T20", # flake8-print
    "Q",   # flake8-quotes
    "W",   # pycodestyle warnings
    "YTT", # flake8-2020
    "ERA", # flake8-eradicate
]
extend-select = [
    "ANN001", #  type annotation for function argument
    "ANN201", #  return type annonation public function
    "ANN205", #  return type annonation static method
    "ANN401", #  any type annotation
    "BLE001", #  blind exception
    "D107",   #  missing docstring in __init__
    "D417",   #  undocumented-parameter
]
ignore = [
    "N999",   #  invalid module name
    "COM812", #  missing-trailing-comma (conflict with formatter)
    "SIM108", #  if-else-block-instead-of-if-exp
]

[tool.ruff.lint.isort]
force-single-line = false
split-on-trailing-comma = false

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = false

[tool.typos.default]
locale = "en-us"

```

### Full pre-commit config:

```yaml
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: ^.vscode/
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff # linter
        args: [--fix]
      - id: ruff-format # formatter

  - repo: https://github.com/crate-ci/typos
    rev: v1.21.0
    hooks:
      - id: typos

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        pass_filenames: false
        always_run: true
        args: [src, tests, examples]
        additional_dependencies:
          - numpy
          - matplotlib
          - pytest
          - ...
```

These settings are kind of strict (which might mean you have to adjust your code before beeing able to commit something), but my experience is that this really pays off on the long run. 

Of course we could remove some rules or at least disable them in the beginning, but a lot of things will be done by the ruff formatter automatically anyway. 

I am happy to hear your opinions.

### PR DESCRIPTION
**Pull request by schuenke**
closes #197 

Probably nobody wants to review all changes manually, but maybe you can checkout this PR and just check that your last ~10 pypulseq sequences and/or related projects still work fine @FrankZijlstra @btasdelen and maybe even @mavel101 @wtclarke 

IMO, this is a necessary step towards a better maintainable package and it will simplify to proceed with #95 and #123

## Some infos about pre-commit:

- I added pre-commit as an optional "test" dependency in `pyproject.toml`
- I added a pre-commit GitHub workflow that runs in every PR (and it has to pass to be able to merge the PR)
- you can download pre-commit from PyPi using `pip install pre-commit`
- after downloading, it can be installed using the `pre-commit install` command
- when installed, it will run locally every time BEFORE you create a commit. This way you directly know if it will pass the GitHub workflow
- if you still want to commit something that does NOT pass all pre-commit hooks, you can skip the pre-commit checks using `git commit -m "your msg" --no-verify`. Note that this does NOT skip the pre-commit GitHub workflow.
- additional hooks I would like to add in the future: mypy, check-docstring-first

## Some further infos about RUFF:

- [RUFF](https://docs.astral.sh/ruff/) is "an extremely fast Python linter and code formatter"
- it is used in many large projects like FastAPI, scipy, pandas, ...
- it supports over 800 different rules
- it supports a hierarchical configuration (different configs for subfoldes like `tests` or `seq_examples`)
- editor integrations for VsCode and my other editors are available (I highly recommend it!)
- I already added some additional rules that I would like to enforce in the future. These are commented out in RUFF section of the `pyproject.toml` file.

### CODE REVIEW

**Review by btasdelen — APPROVED** [review]
Looks good. I tested with a couple sequence, did not see any issues.

**Comment by schuenke** [comment]
I also added the config for [pre-commi ci](https://pre-commit.ci/) now. This allows automated fixes in PRs and will check monthly for updates of the different pre-commit hooks that we use. If we want to activate it, @sravan953 hast to login at https://pre-commit.ci/ and add an installation for pypulseq (just select the repo - thats all).

**Comment by schuenke** [comment]
@FrankZijlstra are you fine with merging it? Or you wanna have some extra time to review it as well?

**Comment by FrankZijlstra** [comment]
I had a quick look and though I'm not familiar with RUFF and how to set it up, from looking at the style changes in the files I think it looks good. Maybe it would be a good idea to add a note to the readme about how to set up pre-commit (basically what you put here)?

I haven't tested it with my sequences, but looking at the changes I don't see anything that would break. So I'm fine with committing this now.

If I remember correctly I still have a branch where I added all the sequence examples to the test_sequence unit tests. And then it shouldn't be too hard to put the new tests in a PR soon(ish), and we can check a bit more elaborate set of sequences automatically.

**Pull request merged**
