### PR TITLE
Release 1.4.2.post1

### PR DESCRIPTION
**Pull request by schuenke**
Would be great if we could get this merged / released very soon. I have to give a presentation on Thursday and it would be nice to have the latest fixes released 😄

### CODE REVIEW

**Comment by schuenke** [comment]
I prepared the release draft here:
https://github.com/imr-framework/pypulseq/releases

**Comment by schuenke** [comment]
Note sure why GitHub isn't showing the diff of `sequence.py` correctly. The only change is that I added `[:3]` in this line:

```python
major, minor, revision = __version__.split('.')[:3]
```

**Comment by btasdelen** [comment]
@schuenke I suggest we fix #208 before we release. It is trivial, I am fixing it right now.

**Review by btasdelen — APPROVED** [review]
After the conflict in sequence.py is resolved, looks good.

**Comment by schuenke** [comment]
Will add the fix with #219 and create another Release PR after merging #218

**Pull request closed without merging**
