### PR TITLE
Create export_waveforms.py

### PR DESCRIPTION
**Pull request by tonggehua**
This function exports all the waveforms from a given seq object for more flexible visualization.

### CODE REVIEW

**Comment by sravan953** [comment]
Could you please update `tonggehua:dev` with the latest changes from `imr-framework:dev`?

**Comment by tonggehua** [comment]
> Could you please update `tonggehua:dev` with the latest changes from `imr-framework:dev`? I can then proceed to work this PR into the code.

Hi Sravan,

Is it possible to merge this directly? I only see the need to update my fork if the method itself needs to be updated for the new version.

**Comment by tonggehua** [comment]
@sravan953 I have fetched upstream on my fork. Please let me know if it works now.

**Comment by sravan953** [comment]
Done! Hope it helps!

**Pull request merged**
