### PR TITLE
Assert that make_trapezoid() slew rate is smaller than max_slew

### PR DESCRIPTION
**Pull request by h3lg3**
Tries to address #213 

make_trapezoid() checks at the end if system.max_slew is exceeded. Similar to what is done with system.max_grad.

### CODE REVIEW

**Comment by FrankZijlstra** [comment]
Yes, I agree that this should be checked. In addition, the same check should be done for the ramp down, i.e. using `fall_time` instead of `rise_time`.

And is it possible to create a gradient with a `rise_time` of 0.0 (and consequently, an amplitude of 0.0)? If so, the assertion needs to check that to avoid a division by 0.

@schuenke How do we deal with the ruff error in the pre-commit here? Should @h3lg3 run it locally to fix the formatting, or just change the formatting as suggested in the error log (https://github.com/imr-framework/pypulseq/actions/runs/12162263429/job/34029382533?pr=214)?

**Comment by schuenke** [comment]
> @schuenke How do we deal with the ruff error in the pre-commit here? Should @h3lg3 run it locally to fix the formatting, or just change the formatting as suggested in the error log (https://github.com/imr-framework/pypulseq/actions/runs/12162263429/job/34029382533?pr=214)?

Ideally @sravan953 will activate pre-commit.ci for PyPulseq. If this is done, it would be fixed automatically. I asked him at GitHub and Slack, but didn't get a response yet. So for the moment it would be either @h3lg3 fixing it or one of us. Will probably take me 30 secs, so fine for me.

**Comment by schuenke** [comment]
pre-commit.ci autofix

**Comment by schuenke** [comment]
Okay, @sravan953 activated pre-commit ci and it seems to work fine.

**Pull request merged**
